#  -*- coding: utf-8 -*-
# Support module generated by PAGE version 7.4
#  in conjunction with Tcl version 8.6
import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import SynDict


def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = SynDict.window(_top1)
    root.mainloop()

if __name__ == '__main__':
    SynDict.start_up()




